config/routes.rb
Rails.application.routes.draw do
  root 'trips#index'

  devise_for :users

  resources :trips
  resources :locations

  get '/trip/:id/find_location/:id', to: 'trips#find_location', as: 'find_location'
  patch '/trip/:id/add_location/', to: 'trips#add_location', as: 'add_location'
  patch '/trip/:id/remove_location/:trip_id', to: 'trips#remove_from_trip', as: 'remove_location'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip, optional: true

  geocoded_by :address
  after_validation :geocode
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :locations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trips, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :find_location, only: [:edit, :show, :update, :destroy ]

  def index
    @locations = Location.all.order(created_at: :desc).paginate(page: params[:page], per_page: 15)
  end

  def show
  end

  def new
    @location = Location.new
  end

  def edit
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      flash[:success] = "You added a location!"

      redirect_to locations_path
    else
      render :new
    end
  end

  def update
    if @location.update(location_params)
      flash[:success] = "Location Updated!"

      redirect_to locations_path
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    flash[:success] = "Location removed!"

    redirect_to locations_path
  end

  private


    def find_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:address, :name, :country, :description)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy,
                                  :find_location, :add_location, :remove_from_trip]

  def index
    @trip = current_user.trips.order(created_at: :desc)
  end

  def show
    locations = @trip.locations
    @hash = Gmaps4rails.build_markers(locations) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
      marker.infowindow location.description
    end
  end

  def new
    @trip = current_user.trips.new
  end

  def edit
  end

  def create
    @trip = current_user.trips.create(trip_params)
    if @trip.save
      flash[:success] = "You Successfully Created A Trip!"
      redirect_to trips_path
    else
      render :new
    end
  end

  def update
    @trip = current_user.trips.find(params[:id])
    if @trip.update(trip_params)
      flash[:success] = "You updated your trip!"

      redirect_to trip_path(@trip)
    else
      render :edit
    end
  end

  def destroy
    current_user.trips.find(params[:id]).destroy
    flash[:success] = "Trip successfully removed!"

    redirect_to trips_path
  end

  #custom controllers for adding locations

  def find_location
    @locations = Location.where('trip_id IS ?', nil).order(created_at: :desc).paginate(page: params[:page], per_page: 15)
  end

  def add_location
    @location = Location.find(params[:format])
    @location.update(trip_id: params[:id])
    flash[:success] = "Location Added!"
    redirect_to trip_path(@trip)
  end

  def remove_from_trip
    @location = Location.find(params[:trip_id])
    @location.update(trip_id: nil)
    flash[:alert] = "Location Removed!"
    redirect_to trip_path(@trip)
  end

  private
    def trip_params
      params.require(:trip).permit(:name, :days, :season, :description)
    end

    def set_trip
      @trip = current_user.trips.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrickTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>

  </head>
  <body>




      <%= render '/shared/nav' %>
      <%= yield %>



      <%= render '/shared/footer' %>
  </body>

</html>

app/views/locations/_form.html.erb
<div class="ui container center">
  <div class="ui medium form">
    <div class="three fields">
    <div class="field">
      <div class="ui inverted segment">
  <div class="ui inverted form">

  <%= form_for @location, class: "ui form" do |f| %>

  <div class'field'>
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
  </div>

  <div class'field'>
    <%= f.label :country %>
    <%= f.text_field :country, required: true%>
  </div>

  <div class'field'>
    <%= f.label :address %>
    <%= f.text_field :address, required: true%>
  </div>

  <br>

  <div class'field'>
    <%= f.label :description %>
    <%= f.text_area :description%>
  </div>

  <%= f.submit class: "ui blue button" %>


  <% end %>
</div>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>

<%= render 'form' %>

app/views/locations/index.html.erb
<%= render '/shared/flash' %>

<div class="ui container" >
    <div class"ui grid">


      <div class="location-head">
        <h1>Select from many locations OR make your own</h1>
        <h2 class="ui center aligned icon header">
  <i class="globe icon"></i>
</h2>

        <%= link_to "Back to Trips", trips_path, class: 'ui gray button' %>
        <%= link_to "New location", new_location_path(@location), class: 'ui gray button' %>
        <div class="ui form">
          <br>



  <div class="ui gray button">
    <label>Select Location</label>
    <select class="ui search dropdown">
      <option value="">Select Country</option>
      <option value="AF">Afghanistan</option>
      <option value="AX">Åland Islands</option>
      <option value="AL">Albania</option>
      <option value="DZ">Algeria</option>
      <option value="AS">American Samoa</option>
      <option value="AD">Andorra</option>
      <option value="AO">Angola</option>
      <option value="AI">Anguilla</option>
      <option value="AQ">Antarctica</option>
      <option value="AG">Antigua and Barbuda</option>
      <option value="AR">Argentina</option>
      <option value="AM">Armenia</option>
      <option value="AW">Aruba</option>
      <option value="AU">Australia</option>
      <option value="AT">Austria</option>
      <option value="AZ">Azerbaijan</option>
      <option value="BS">Bahamas</option>
      <option value="BH">Bahrain</option>
      <option value="BD">Bangladesh</option>
      <option value="BB">Barbados</option>
      <option value="BY">Belarus</option>
      <option value="BE">Belgium</option>
      <option value="BZ">Belize</option>
      <option value="BJ">Benin</option>
      <option value="BM">Bermuda</option>
      <option value="BT">Bhutan</option>
      <option value="BO">Bolivia, Plurinational State of</option>
      <option value="BQ">Bonaire, Sint Eustatius and Saba</option>
      <option value="BA">Bosnia and Herzegovina</option>
      <option value="BW">Botswana</option>
      <option value="BV">Bouvet Island</option>
      <option value="BR">Brazil</option>
      <option value="IO">British Indian Ocean Territory</option>
      <option value="BN">Brunei Darussalam</option>
      <option value="BG">Bulgaria</option>
      <option value="BF">Burkina Faso</option>
      <option value="BI">Burundi</option>
      <option value="KH">Cambodia</option>
      <option value="CM">Cameroon</option>
      <option value="CA">Canada</option>
      <option value="CV">Cape Verde</option>
      <option value="KY">Cayman Islands</option>
      <option value="CF">Central African Republic</option>
      <option value="TD">Chad</option>
      <option value="CL">Chile</option>
      <option value="CN">China</option>
      <option value="CX">Christmas Island</option>
      <option value="CC">Cocos (Keeling) Islands</option>
      <option value="CO">Colombia</option>
      <option value="KM">Comoros</option>
      <option value="CG">Congo</option>
      <option value="CD">Congo, the Democratic Republic of the</option>
      <option value="CK">Cook Islands</option>
      <option value="CR">Costa Rica</option>
      <option value="CI">Côte d'Ivoire</option>
      <option value="HR">Croatia</option>
      <option value="CU">Cuba</option>
      <option value="CW">Curaçao</option>
      <option value="CY">Cyprus</option>
      <option value="CZ">Czech Republic</option>
      <option value="DK">Denmark</option>
      <option value="DJ">Djibouti</option>
      <option value="DM">Dominica</option>
      <option value="DO">Dominican Republic</option>
      <option value="EC">Ecuador</option>
      <option value="EG">Egypt</option>
      <option value="SV">El Salvador</option>
      <option value="GQ">Equatorial Guinea</option>
      <option value="ER">Eritrea</option>
      <option value="EE">Estonia</option>
      <option value="ET">Ethiopia</option>
      <option value="FK">Falkland Islands (Malvinas)</option>
      <option value="FO">Faroe Islands</option>
      <option value="FJ">Fiji</option>
      <option value="FI">Finland</option>
      <option value="FR">France</option>
      <option value="GF">French Guiana</option>
      <option value="PF">French Polynesia</option>
      <option value="TF">French Southern Territories</option>
      <option value="GA">Gabon</option>
      <option value="GM">Gambia</option>
      <option value="GE">Georgia</option>
      <option value="DE">Germany</option>
      <option value="GH">Ghana</option>
      <option value="GI">Gibraltar</option>
      <option value="GR">Greece</option>
      <option value="GL">Greenland</option>
      <option value="GD">Grenada</option>
      <option value="GP">Guadeloupe</option>
      <option value="GU">Guam</option>
      <option value="GT">Guatemala</option>
      <option value="GG">Guernsey</option>
      <option value="GN">Guinea</option>
      <option value="GW">Guinea-Bissau</option>
      <option value="GY">Guyana</option>
      <option value="HT">Haiti</option>
      <option value="HM">Heard Island and McDonald Islands</option>
      <option value="VA">Holy See (Vatican City State)</option>
      <option value="HN">Honduras</option>
      <option value="HK">Hong Kong</option>
      <option value="HU">Hungary</option>
      <option value="IS">Iceland</option>
      <option value="IN">India</option>
      <option value="ID">Indonesia</option>
      <option value="IR">Iran, Islamic Republic of</option>
      <option value="IQ">Iraq</option>
      <option value="IE">Ireland</option>
      <option value="IM">Isle of Man</option>
      <option value="IL">Israel</option>
      <option value="IT">Italy</option>
      <option value="JM">Jamaica</option>
      <option value="JP">Japan</option>
      <option value="JE">Jersey</option>
      <option value="JO">Jordan</option>
      <option value="KZ">Kazakhstan</option>
      <option value="KE">Kenya</option>
      <option value="KI">Kiribati</option>
      <option value="KP">Korea, Democratic People's Republic of</option>
      <option value="KR">Korea, Republic of</option>
      <option value="KW">Kuwait</option>
      <option value="KG">Kyrgyzstan</option>
      <option value="LA">Lao People's Democratic Republic</option>
      <option value="LV">Latvia</option>
      <option value="LB">Lebanon</option>
      <option value="LS">Lesotho</option>
      <option value="LR">Liberia</option>
      <option value="LY">Libya</option>
      <option value="LI">Liechtenstein</option>
      <option value="LT">Lithuania</option>
      <option value="LU">Luxembourg</option>
      <option value="MO">Macao</option>
      <option value="MK">Macedonia, the former Yugoslav Republic of</option>
      <option value="MG">Madagascar</option>
      <option value="MW">Malawi</option>
      <option value="MY">Malaysia</option>
      <option value="MV">Maldives</option>
      <option value="ML">Mali</option>
      <option value="MT">Malta</option>
      <option value="MH">Marshall Islands</option>
      <option value="MQ">Martinique</option>
      <option value="MR">Mauritania</option>
      <option value="MU">Mauritius</option>
      <option value="YT">Mayotte</option>
      <option value="MX">Mexico</option>
      <option value="FM">Micronesia, Federated States of</option>
      <option value="MD">Moldova, Republic of</option>
      <option value="MC">Monaco</option>
      <option value="MN">Mongolia</option>
      <option value="ME">Montenegro</option>
      <option value="MS">Montserrat</option>
      <option value="MA">Morocco</option>
      <option value="MZ">Mozambique</option>
      <option value="MM">Myanmar</option>
      <option value="NA">Namibia</option>
      <option value="NR">Nauru</option>
      <option value="NP">Nepal</option>
      <option value="NL">Netherlands</option>
      <option value="NC">New Caledonia</option>
      <option value="NZ">New Zealand</option>
      <option value="NI">Nicaragua</option>
      <option value="NE">Niger</option>
      <option value="NG">Nigeria</option>
      <option value="NU">Niue</option>
      <option value="NF">Norfolk Island</option>
      <option value="MP">Northern Mariana Islands</option>
      <option value="NO">Norway</option>
      <option value="OM">Oman</option>
      <option value="PK">Pakistan</option>
      <option value="PW">Palau</option>
      <option value="PS">Palestinian Territory, Occupied</option>
      <option value="PA">Panama</option>
      <option value="PG">Papua New Guinea</option>
      <option value="PY">Paraguay</option>
      <option value="PE">Peru</option>
      <option value="PH">Philippines</option>
      <option value="PN">Pitcairn</option>
      <option value="PL">Poland</option>
      <option value="PT">Portugal</option>
      <option value="PR">Puerto Rico</option>
      <option value="QA">Qatar</option>
      <option value="RE">Réunion</option>
      <option value="RO">Romania</option>
      <option value="RU">Russian Federation</option>
      <option value="RW">Rwanda</option>
      <option value="BL">Saint Barthélemy</option>
      <option value="SH">Saint Helena, Ascension and Tristan da Cunha</option>
      <option value="KN">Saint Kitts and Nevis</option>
      <option value="LC">Saint Lucia</option>
      <option value="MF">Saint Martin (French part)</option>
      <option value="PM">Saint Pierre and Miquelon</option>
      <option value="VC">Saint Vincent and the Grenadines</option>
      <option value="WS">Samoa</option>
      <option value="SM">San Marino</option>
      <option value="ST">Sao Tome and Principe</option>
      <option value="SA">Saudi Arabia</option>
      <option value="SN">Senegal</option>
      <option value="RS">Serbia</option>
      <option value="SC">Seychelles</option>
      <option value="SL">Sierra Leone</option>
      <option value="SG">Singapore</option>
      <option value="SX">Sint Maarten (Dutch part)</option>
      <option value="SK">Slovakia</option>
      <option value="SI">Slovenia</option>
      <option value="SB">Solomon Islands</option>
      <option value="SO">Somalia</option>
      <option value="ZA">South Africa</option>
      <option value="GS">South Georgia and the South Sandwich Islands</option>
      <option value="SS">South Sudan</option>
      <option value="ES">Spain</option>
      <option value="LK">Sri Lanka</option>
      <option value="SD">Sudan</option>
      <option value="SR">Suriname</option>
      <option value="SJ">Svalbard and Jan Mayen</option>
      <option value="SZ">Swaziland</option>
      <option value="SE">Sweden</option>
      <option value="CH">Switzerland</option>
      <option value="SY">Syrian Arab Republic</option>
      <option value="TW">Taiwan, Province of China</option>
      <option value="TJ">Tajikistan</option>
      <option value="TZ">Tanzania, United Republic of</option>
      <option value="TH">Thailand</option>
      <option value="TL">Timor-Leste</option>
      <option value="TG">Togo</option>
      <option value="TK">Tokelau</option>
      <option value="TO">Tonga</option>
      <option value="TT">Trinidad and Tobago</option>
      <option value="TN">Tunisia</option>
      <option value="TR">Turkey</option>
      <option value="TM">Turkmenistan</option>
      <option value="TC">Turks and Caicos Islands</option>
      <option value="TV">Tuvalu</option>
      <option value="UG">Uganda</option>
      <option value="UA">Ukraine</option>
      <option value="AE">United Arab Emirates</option>
      <option value="GB">United Kingdom</option>
      <option value="US">United States</option>
      <option value="UM">United States Minor Outlying Islands</option>
      <option value="UY">Uruguay</option>
      <option value="UZ">Uzbekistan</option>
      <option value="VU">Vanuatu</option>
      <option value="VE">Venezuela, Bolivarian Republic of</option>
      <option value="VN">Viet Nam</option>
      <option value="VG">Virgin Islands, British</option>
      <option value="VI">Virgin Islands, U.S.</option>
      <option value="WF">Wallis and Futuna</option>
      <option value="EH">Western Sahara</option>
      <option value="YE">Yemen</option>
      <option value="ZM">Zambia</option>
      <option value="ZW">Zimbabwe</option>



    </select>
  </div>
</div>



      </div>

      <%= will_paginate  %>

      <div id="location-index" class "sixteen wide computer column">
        <div class="ui cards">
          <% @locations.each do |local| %>


          <div class="card local">
            <div class="content">
              <div class="header">
                <%=link_to local.name, location_path(local) %>
              </div>

              <div class="description">
                <%= local.country %>
              </div>
              <div class="description">
                <%= local.address %>
              </div>
            </div>
            <div class="extra content">
            </div>
          </div>
          <% end %>
        </div>
      </div>

      <%= will_paginate %>


    </div>
  </div>

app/views/locations/new.html.erb
<h1>Create a new location</h1>

<%= render 'form' %>

app/views/locations/show.html.erb
<%= render '/shared/flash' %>

<div class="ui container">
  <h1><%= @location.name %></h1>

  <p><strong>Country:&thinsp;</strong> <%= @location.country %></p>
  <p><strong>Address:&thinsp;</strong> <%= @location.address %></p>
  <p><strong>Description:&thinsp;</strong> <%= @location.description %></p>

  <%= link_to "Back to All locations", locations_path(@location), class: "ui blue button" %>
  <%= link_to "Edit", edit_location_path(@location), class: "ui orange button" %>
  <%= link_to "Remove", location_path(@location),
                        method: :delete, data: {confirm: 'Are you sure?'},
                        class: "ui red button" %>
</div>

app/views/shared/_errors.html.erb
<% if @trip.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<div class="flash-messages">
  <% flash.each do |type, message| %>
  <div class="flash <%= type %>">
    <p>
      <%= message %>
    </p>
  </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div id="page-footer">
  <div class="ui bottom fixed menu ui grid">

    <div class="four column row">
      <div class="column">
        <p>Copyright © 2017 Travel More Co.</p>

      </div>
      <div class="column">
        <p><i class="mail icon"></i>  travelmore@travel.com</p>
      </div>
      <div class="column"></div>
      <div id="flex-wrapper" class="column">
        <i class="retweet icon"></i>
        <i class="pied piper hat icon"></i>
        <i class="marker icon"></i>
        <i class="paypal icon"></i>
        <i class="instagram icon"></i>

      </div>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="ui top fixed menu header">



  <%= link_to 'Home', root_path, class: "item"%>
  <%= link_to 'Trips', trips_path, class: "item"%>
  <%= link_to 'Locations', locations_path, class: "item"%>
  <% if user_signed_in? %>
    <div>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete,class: "item"%>
    </div>
  <% else %>
    <%= link_to "Sign up", new_registration_path(resource_name), class: 'item' %>
  <% end %>
</div>

app/views/trips/_each_location.html.erb
      <div class "sixteen wide computer column">
        <div class="ui cards">
          <% @trip.locations.each do |local| %>


          <div class="card">
            <div class="content">
              <div class="header">
                <%=link_to local.name, location_path(local) %>
              </div>

              <div class="description">
                <%= local.country %>
              </div>
              <div class="description">
                <%= local.address %>
              </div>
              <div class="description">
                <strong>Description: </strong><%= local.description.truncate(65) %>
              </div>
            </div>
            <div class="extra content">
              <%= link_to 'Remove This location', remove_location_path(@trip, local), method: :patch, class: "ui basic orange button" %>
            </div>
          </div>
          <% end %>
        </div>
      </div>

app/views/trips/_form.html.erb
     <h1 class="ui center aligned icon header">Add A Trip</h1>
     <div class="ui form">

       <h2 class="ui center aligned icon header">
 <i class="globe icon"></i>
 </h2>

     <br>
     <br>

<div id="form-model">
<%= form_for @trip do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: 'Name your trip', required: true %>
  <%= f.label :days %>
  <%= f.number_field :days, required: true, placeholder: '?' %>
  <%= f.label :season %>
  <%= f.select :season, ['Summer', 'Autumn', 'Winter', 'Spring'], required: true %>
  <%= f.label :description %>
  <%= f.text_area :description, placeholder: 'Add a description'%>
  <%= f.submit class: "ui green button" %>
<% end %>

     </div>
</div>

app/views/trips/_gmap.html.erb
<div style='width: 500px;'>
  <div id="map" style='width: 500px; height: 250px;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.map.centerOn({ lat: 40.761215, lng: -111.882853 })
  handler.fitMapToBounds();
  handler.getMap().setZoom(6);
});

</script>

app/views/trips/_scripts.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyD7XRZtYwQHSBXGSbM8c9KmloGhVgisKzY"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

app/views/trips/_trip_info.html.erb
  <div class="eight wide column">
    <p>
      <strong>Your trip</strong>
      <p id="trip-name">
        <%= @trip.name %>

      </p>
    </p>
    <p>
      <strong>Duration:</strong>
      <%= @trip.days %> Days
    </p>
    <p>
      <strong>Season:</strong>
      <%= @trip.season %>
    </p>

    <div class="trip-buttons">
      <%= link_to 'Edit Trip', edit_trip_path(@trip), class: "ui orange button" %>
      <%= link_to 'Delete', trip_path(@trip), method: :delete,
      data: {confirm: 'Are you sure you would like to delete?'},
      class: "ui red button" %>

    </div>

  </div>
  <div id="description-trip" class="eight wide column ">
    <strong>Description:</strong>
    <p><%= @trip.description %></p>
  </div>

app/views/trips/edit.html.erb
<div class='ui container'>
  <h1>Editing: <%= @trip.name%></h1>

  <%= render 'form' %>
</div>

app/views/trips/find_location.html.erb
<div id="location-main" class="ui container">
    <div id="center" class"ui center aligned page grid ">
      <h1>Pick your location</h1>

      <div id="but-contain" class="ui two buttons">
        <%= link_to "Back to Trips", trips_path, class: 'ui green button' %>
        <%= link_to "Create New location", new_location_path(@location), class: 'ui purple blue button' %>
      </div>

      <%= will_paginate @locations %>
      <div class="locations-all">
          <div class="ui cards">
            <% @locations.each do |local| %>


            <div class="card">
              <div class="content">
                <div class="header">
                  <%=link_to local.name, location_path(local) %>
                </div>

                <div class="description">
                  <%= local.country %>
                </div>
                <div class="description">
                  <%= local.address %>
                </div>
                <div class="description">
                  <%= local.description %>
                </div>
              </div>
              <div class="extra content">
                <%= link_to 'Add This Location', add_location_path(@trip, local), method: :patch, class: "ui basic green button" %>
              </div>
            </div>
            <% end %>
          </div>

      </div>

      <%= will_paginate @locations %>

    </div>
  </div>

app/views/trips/index.html.erb
<%= render '/shared/flash' %>

<div id="trip-show">
  <div class="ui two column centered grid">
    <div class="column">

      <div id="trip-show">
        <h1><%= current_user.first_name%>'s Trips</h1>

        <div id="trip-buttons">

          <%= link_to 'Add New Trip', new_trip_path, class: 'ui purple button' %>
          <%= link_to 'View All locations', locations_path, class: 'ui green button' %>

        </div>
      </div>

      <div id="index-view" class='ui container'>



        <% if @trip.any? %>
        <% @trip.each do |trip| %>
        <div class="ui card">
          <div class="content card-top">
            <div class="right floated meta"><%= trip.days %> Days</div>
            <%= link_to trip.name, trip_path(trip) %>
          </div>
          <div class="image">
            <%= image_tag 'index_image.jpg' %>
          </div>
          <div class="content card-bottom">
            <span class="right floated">
              <i class="heart outline like icon"></i>
              <%= rand(1..21) %> Likes
            </span>
            <i class="remove from calendar icon"></i>
            <%= trip.season %>
          </div>
        </div>
        <% end %>
        <% else %>
        <h4>Create a trip!</h4>
        <% end %>


      </div>

    </div>

  </div>

</div>

app/views/trips/new.html.erb
<div class='ui container'>


  <h1>Add Trip</h1>
  <%= render '/shared/errors' %>
  <%= render 'form' %>
</div>

app/views/trips/show.html.erb
<%= render 'scripts' %>
<%= render '/shared/flash' %>

<div  class="ui container" id="location-wrapper">

  <div class="ui grid">


    <div class="sixteen wide column">
      <h1><%= current_user.first_name %>'s <%= @trip.name %></h1>

    </div>

      <div class="eight wide column">
        <%= render 'gmap' %>
      </div>

      <div class="eight wide column">
        <div id="flex-wrapper2" class="ui grid">
          <%= render 'trip_info' %>
        </div>
      </div>


  </div>

</div>

<div class="ui container">
<div class="all-locations">

<div id="all-locations" class="ui container">
  <div class"ui grid">
    <h1>Places to Visit</h1>
    <div class="location-buttons">
      <%= link_to 'Add a location', find_location_path, class: "ui teal button" %>
      <%= link_to "New location", new_location_path(@location), class: "ui green button"%>
    </div>
    <% if @trip.locations.any? %>
      <%= render 'each_location' %>
    <% else %>
      <h3>Add a trip!</h3>
    <% end %>
  </div>
</div>